---
name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  readme-gen:
    name: Generate README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: toozej/monogo/apps/github-readme-gen@main
        with:
          user: toozej
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit generated README
        run: |
          set -euo pipefail

          git config user.name 'readme-gen 🤖'
          git config user.email actions@github.com
          git add -- README.md
          if git diff --cached --quiet; then
            exit 0
          fi

          git commit --message 'Update generated README'
          git push
